# permissions for end users to edit configdeployments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: configdeployment-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: demo-crd2
    app.kubernetes.io/part-of: demo-crd2
    app.kubernetes.io/managed-by: kustomize
  name: configdeployment-editor-role
rules:
- apiGroups:
  - apps.x893675.github.io
  resources:
  - configdeployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.x893675.github.io
  resources:
  - configdeployments/status
  verbs:
  - get
