---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - demo.x893675.github.io
  resources:
  - guestbooks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - demo.x893675.github.io
  resources:
  - guestbooks/finalizers
  verbs:
  - update
- apiGroups:
  - demo.x893675.github.io
  resources:
  - guestbooks/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - iam.x893675.github.io
  resources:
  - tokens
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - iam.x893675.github.io
  resources:
  - tokens/finalizers
  verbs:
  - update
- apiGroups:
  - iam.x893675.github.io
  resources:
  - tokens/status
  verbs:
  - get
  - patch
  - update
