# permissions for end users to view tokens.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: token-viewer-role
rules:
- apiGroups:
  - iam.x893675.github.io
  resources:
  - tokens
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - iam.x893675.github.io
  resources:
  - tokens/status
  verbs:
  - get
